#!/usr/bin/env bash
# Minimal install script for: AMD64

# install core tools
sudo apt install -y zsh vim fzf fasd tmux silversearcher-ag python locate tree

# install bat
wget https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb && sudo dpkg -i bat*.deb


# install cheat
wget https://github.com/cheat/cheat/releases/download/4.0.2/cheat-linux-amd64.gz
gzip -d cheat-linux-amd64.gz
mv cheat-linux-amd64 ~/bin/cheat && chmod +x ~/bin/cheat



# manually clone fzf
sudo mkdir -p /opt/fzf
sudo chown $USER /opt/fzf
sudo git clone https://github.com/junegunn/fzf.git /opt/fzf

# download dotfiles
wget -O- smirnov.link/d | sh

# initialize locate db
sudo updatedb

