#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` or `git checkout` if a specified file was changed
# Run `chmod +x post-checkout` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && echo " * changes detected in $1" && echo " *
running $2" && eval "$2"
}

# Generate i3 config if changes detected
check_run i3 "~/.dotfiles/i3/loader"
check_run .conf.yaml "~/.dotfiles/upgrade.sh"
