filetype off                  " required

" The following block sets up Vundle. Check github for README.
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" colors
Plugin 'jacoborus/tender'

" statusline
Plugin 'itchyny/lightline.vim'

" comments
Plugin 'tpope/vim-commentary'

" additional file types
Plugin 'fatih/vim-nginx'

" exapnd region - press v repeatedly
Plugin 'terryma/vim-expand-region'
"go packages"
Plugin 'fatih/vim-go'

call vundle#end()            " required
filetype plugin indent on    " required
" End Vundle config.


"" Basics
syntax enable
set encoding=utf-8
set showcmd                     " display incomplete commands
set number                          " enable line numbers
set autoindent                          " set auto-indenting on for programming
set showmatch                   " automatically show matching brackets. works like it does in bbedit.
set visualbell                          " turn on the "visual bell" - which is much quieter than the "audio blink"
set ruler                       " show the cursor position all the time
set backspace=indent,eol,start  " make that backspace key work the way it should
"set background=dark             " Use colours that work well on a dark background (Console is usually black)
"set showmode                    " show the current mode
"set clipboard=unnamed           " set clipboard to unnamed to access the system clipboard under windows


"" Leader
let g:mapleader="\<Space>"

""  leader shortcuts
" :W saves the file with sudo.  must come before the <leader>w remap below
command W w !sudo tee % > /dev/null
" quickly save files
nnoremap <Leader>w :w<CR>

" system clipboard
set clipboard=unnamedplus
map <leader>y "+y  

"" Colors
colorscheme tender
"hi Visual guibg=#5f5f5f ctermbg=59            " manual override.
hi Visual term=reverse cterm=reverse guibg=#5f5f5f

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=4 shiftwidth=4      " a tab is two spaces
set expandtab                   " use spaces, not tabs
set backspace=indent,eol,start  " backspace through everything in insert mode
command! KillWhitespace :normal :%s/ *$//g<cr><c-o><cr>

"" Splits
set splitright
set splitbelow

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

""" lightline settings """
" enable tender theme
let g:tender_lightline = 1
" set lightline theme
let g:lightline = { 
    \ 'colorscheme': 'tender',
    \ 'component' : {
    \   'readonly': '%{&filetype=="help"?"":&readonly?"-":""}',
    \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
    \ },
    \ 'component_visible_condition': {
    \   'readonly': '(&filetype!="help"&& &readonly)',
    \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))'
    \ },
    \ 'active' : {
    \    'right' : [ [ 'lineinfo' ], [ 'percent' ], [ 'filetype' ] ]
    \ },
  \ }
if !has('gui_running')
  set t_Co=256
endif
set laststatus=2
set noshowmode

" http://www.blaenkdenum.com/posts/a-simpler-vim-statusline/
" mode aware cursors (NOTE: Gui Only)
set guicursor=a:block
set guicursor+=o:hor50-Cursor
set guicursor+=n:Cursor
set guicursor+=i-ci-sm:InsertCursor
set guicursor+=r-cr:ReplaceCursor-hor20
set guicursor+=c:CommandCursor
set guicursor+=v-ve:VisualCursor
set guicursor+=a:blinkon0

hi InsertCursor  ctermfg=15 guifg=#fdf6e3 ctermbg=37  guibg=#2aa198
hi VisualCursor  ctermfg=15 guifg=#fdf6e3 ctermbg=125 guibg=#d33682
hi ReplaceCursor ctermfg=15 guifg=#fdf6e3 ctermbg=65  guibg=#dc322f
hi CommandCursor ctermfg=15 guifg=#fdf6e3 ctermbg=166 guibg=#cb4b16

" line number colors.
"hi CursorLineNr   term=bold ctermfg=Yellow gui=bold guifg=Yellow
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Quickly edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" golang
let g:go_fmt_command = "goimports"
au FileType go nmap <leader>b <Plug>(go-build)

" expand regions (github.com/terryma/vim-expand-region)
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" vp doesn't replace paste buffer
function! RestoreRegister()
    let @" = s:restore_reg
    return ''
endfunction
function! s:Repl()
    let s:restore_reg = @"
    return "p@=RestoreRegister()\<cr>"
endfunction
vmap <silent> <expr> p <sid>Repl()
