# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  run:
    docker:
      - image: ubuntu
    working_directory: ~/.dotfiles
    steps:
      - checkout
      - run: apt update && apt install -y python3 git wget vim curl zsh jq # install curl and zsh
      - run: mkdir -p ~/.i3 ~/.config # make i3 dir for linking targets
      - run: export U=$(curl https://github.cache.smirnov.cloud/repos/sharkdp/bat/releases/latest | jq -r -c 'first(.assets[] | select(.browser_download_url | contains("amd64"))) | .browser_download_url') && wget $U && dpkg -i $(basename $U) # install bat.
      - run: ./install # test install script - vim, bat, etc
      - run: cd zsh && if [[ $(grep -r '#!/bin/zsh' . --exclude-dir=zgen) ]]; then echo "Found malformed shebangs"; exit 1;fi # zsh linter
workflows:
  version: 2
  run_wf:
    jobs:
      - run
