#!/usr/bin/env zsh

ROOT="$HOME/.dotfiles/i3"
NAME=$(echo $HOST | cut -f1 -d".")

# remove the old config. 
mv $ROOT/config /tmp/i3-config.bak

# generate new config
cp $ROOT/snippets/base $ROOT/config

if [ -f $ROOT/profiles/$NAME  ]; then
    echo "Running $NAME config generator"
    source $ROOT/profiles/$NAME
fi

