#!/bin/zsh

ROOT="$HOME/.dotfiles/i3"
NAME=$(echo $HOST | cut -f1 -d".")

# remove the old config. 
mv $ROOT/config /tmp/i3-config.bak

# generate new config
cp $ROOT/includes/base $ROOT/config

if [ -f $ROOT/loaders/$NAME  ]; then
    echo "Running $NAME loader"
    source $ROOT/loaders/$NAME
fi

