#!/bin/bash
# Opens rofi and takes a new name for a workspace.
# Currently focused window is moved to that workspace.

name=$($HOME/.dotfiles/i3/scripts/i3_list_workspaces.sh | rofi -dmenu -p "Move window to workspace: " -i)
if [ $? -eq 0 ]; then
    i3-msg "move window to workspace $name"
fi
