#!/usr/bin/env bash

# setup script, called by dotbot

# check if zsh is even installed
hash zsh 2>/dev/null || { echo >&2 "I require zsh but it's not installed.  Install it."; exit 1;}

# change shell to zsh
if [ $(basename $SHELL) == "zsh" ]; then
    # already zsh
    echo 'shell already zsh, no changes needed'
else
    # Try with sudo, fallback to without if needed.
    sudo chsh -s $(which zsh) $(whoami) || chsh -s $(which zsh) $(whoami)
fi
