####################################################
# Load github.com/tarjoilija/zgen and initialize it.
source "${HOME}/.dotfiles/zsh/zgen/zgen.zsh"
ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zshrc.local ${HOME}/.dotfiles/zsh/zshrc )

# create zgen init script if it doesn't exist
if ! zgen saved; then
  	zgen oh-my-zsh

  	plugins=(git git-extras history brew common-aliases osx tmux)
	plugins+=(z extract adb vagrant )
  	for p in ${(@s' ')plugins}; do
  		zgen oh-my-zsh plugins/$p
  	done

	zgen load ~/.dotfiles/zsh/config/zsh-autosuggestions.zsh
	zgen load zsh-users/zsh-autosuggestions
	zgen load zsh-users/zsh-completions
	zgen load djui/alias-tips
	#zgen load romkatv/zsh-prompt-benchmark

	# As per instructions, load this last so that it wraps ZLE widgets.
	zgen load zsh-users/zsh-syntax-highlighting

	# generate the init script from plugins above
	zgen save
fi

########################################################
# Load custom config last, so it can override plugins ##
find ~/.dotfiles/zsh/config ~/.dotfiles/zsh/aliases -type f -name '*.zsh' -print0 | sort -z |
while IFS= read -r -d $'\0' line; do
	source "$line"
done

# Enable all completions
autoload -U compinit && compinit

# As per instructions, load this last so that it wraps ZLE widgets.
# source ~/.dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Load local config if present, for final overrides.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
